### ISSUE TITLE
lots of duplicate lines in movie subtitles

### ISSUE THREAD

**Issue by dcsan** [Marsan-Ma-zz/chat_corpus#4]
I did a simple dedupe 

cat movie_subtitles_en.txt | uniq > movie_subtitles_en-uniq.txt

and get a big reduction in size

-rw-r--r--   1 dc  staff    16M Jul  3 12:20 movie_subtitles_en-uniq.txt
-rw-r--r--@  1 dc  staff    24M Jul  3 12:18 movie_subtitles_en.txt

any reasons for this?

**Comment by nmilosev** [comment]
Yes, if person A says something person B replies and A then replies you will have:

A1
B1
B1
A2

(1, 2 are different sentences)

**Comment by dcsan** [comment]
I dont quite understand. you mean if B just repeats what A said? eg A1 == B1 ?

so this is expected that there would be the duplicates, eg B1 B1 twice?

**Comment by nmilosev** [comment]
Nah, I explained it wrong. Imagine a dialog going like this:

```
Person A: Hey there how are you?
Person B: Pretty good! You?
Person A: I'm also good! 
```

In this dataset style it would look like this:

```
Hey there how are you?
Pretty good! You?
Pretty good! You?
I'm also good! 
```

So you see that one line got duplicated. Now imagine a movie dialog with many dialogues between two people. Hope that clears it up. :)

**Comment by dcsan** [comment]
oh so that each dialog item is a pair?

```
Hey there how are you?
Pretty good! You?

Pretty good! You?
I'm also good! 
```

**Comment by nmilosev** [comment]
Yes exactly.

**Comment by dcsan** [comment]
thanks for elaborating.
